In [5]:
import numpy as np 
import pandas as pd

In [ ]:
bikes=pd.read_csv('../datasets/bikes.csv',index_col='datetime',parse_dates=True)

In [7]:
bikes.rename(columns={'count':'total'},inplace=True)

In [8]:
bikes['hora']=bikes.index.hour

In [11]:
bikes_dummies=pd.get_dummies(bikes.index.hour,drop_first=True,dtype=int)

In [12]:
bikes_dummies.head()

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
bikes_dummies.index = bikes.index

In [14]:
bikes_dummies.sample(5)

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
datetime,,,,,,,,,,,,,,,,,,,,,
2011-02-03 09:00:00,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2011-03-01 20:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2012-01-16 21:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2011-10-19 09:00:00,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2011-05-02 15:00:00,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [15]:
a = np.array(((bikes.index.hour)>=7)&(bikes.index.hour<=20))

In [16]:
bikes['dia']=a.astype(int)
bikes['dia'].sample(5)

datetime
2012-08-01 01:00:00    0
2011-04-18 23:00:00    0
2011-12-01 02:00:00    0
2011-09-14 09:00:00    1
2011-07-09 05:00:00    0
Name: dia, dtype: int32

In [17]:
bikes = pd.concat([bikes,bikes_dummies],axis=1)

In [18]:
bikes.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,...,14,15,16,17,18,19,20,21,22,23
datetime,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [20]:
from sklearn.model_selection import  train_test_split

In [21]:
def train_test_rmse(feature_cols):
    X=bikes[feature_cols]
    y=bikes.total
    X_train,X_test,y_train,y_test = train_test_split(X,y,shuffle=False)
    linreg=LinearRegression()
    linreg.fit(X_train,y_train)
    y_pred=linreg.predict(X_test)
    return np.sqrt(metrics.mean_squared_error(y_test,y_pred))

In [22]:
train_test_rmse(['temp','season','humidity'])

208.60652132566108

In [23]:
train_test_rmse(['temp','season','humidity','dia'])

177.27663881641269

In [24]:
train_test_rmse(['temp','season','humidity','hora'])

197.75102530844308

In [25]:
bikes['temp_2']=bikes.temp**2
bikes['humidity_2']=bikes.humidity**2

In [26]:
train_test_rmse(['temp','season','humidity','temp_2','humidity_2'])

208.41860390984573